// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/data/data_source/auth_remote_data_source/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:fitness_app/data/api/auth_api/auth_api_manager.dart' as _i6;
import 'package:fitness_app/data/models/edit_profile/edit_profile_request_model.dart'
    as _i13;
import 'package:fitness_app/data/models/edit_profile/edit_profile_response_model.dart'
    as _i5;
import 'package:fitness_app/data/models/forgot_password/request/forgot_password_request_model.dart'
    as _i10;
import 'package:fitness_app/data/models/forgot_password/request/reset_password_request_model.dart'
    as _i12;
import 'package:fitness_app/data/models/forgot_password/request/verify_code_request_model.dart'
    as _i11;
import 'package:fitness_app/data/models/forgot_password/response/forgot_password_response_model.dart'
    as _i4;
import 'package:fitness_app/data/models/login/request/login_request_model.dart'
    as _i8;
import 'package:fitness_app/data/models/login/response/login_response_model.dart'
    as _i2;
import 'package:fitness_app/data/models/sign_up/request/sign_up_request_body.dart'
    as _i9;
import 'package:fitness_app/data/models/sign_up/response/sign_up_response_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseModel_0 extends _i1.SmartFake
    implements _i2.LoginResponseModel {
  _FakeLoginResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponseModel_1 extends _i1.SmartFake
    implements _i3.SignUpResponseModel {
  _FakeSignUpResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgotPasswordResponseModel_2 extends _i1.SmartFake
    implements _i4.ForgotPasswordResponseModel {
  _FakeForgotPasswordResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseModel_3 extends _i1.SmartFake
    implements _i5.EditProfileResponseModel {
  _FakeEditProfileResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiManager extends _i1.Mock implements _i6.AuthApiManager {
  MockAuthApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.LoginResponseModel> login(
          _i8.LoginRequestModel? loginRequestBody) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequestBody],
        ),
        returnValue:
            _i7.Future<_i2.LoginResponseModel>.value(_FakeLoginResponseModel_0(
          this,
          Invocation.method(
            #login,
            [loginRequestBody],
          ),
        )),
      ) as _i7.Future<_i2.LoginResponseModel>);

  @override
  _i7.Future<_i3.SignUpResponseModel> signUp(
          _i9.SignupRequestBody? signupRequestBody) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [signupRequestBody],
        ),
        returnValue: _i7.Future<_i3.SignUpResponseModel>.value(
            _FakeSignUpResponseModel_1(
          this,
          Invocation.method(
            #signUp,
            [signupRequestBody],
          ),
        )),
      ) as _i7.Future<_i3.SignUpResponseModel>);

  @override
  _i7.Future<_i4.ForgotPasswordResponseModel> forgotPassword(
          _i10.ForgotPasswordRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [requestModel],
        ),
        returnValue: _i7.Future<_i4.ForgotPasswordResponseModel>.value(
            _FakeForgotPasswordResponseModel_2(
          this,
          Invocation.method(
            #forgotPassword,
            [requestModel],
          ),
        )),
      ) as _i7.Future<_i4.ForgotPasswordResponseModel>);

  @override
  _i7.Future<_i4.ForgotPasswordResponseModel> verifyResetCode(
          _i11.VerifyCodeRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [requestModel],
        ),
        returnValue: _i7.Future<_i4.ForgotPasswordResponseModel>.value(
            _FakeForgotPasswordResponseModel_2(
          this,
          Invocation.method(
            #verifyResetCode,
            [requestModel],
          ),
        )),
      ) as _i7.Future<_i4.ForgotPasswordResponseModel>);

  @override
  _i7.Future<_i4.ForgotPasswordResponseModel> resetPassword(
          _i12.ResetPasswordRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [requestModel],
        ),
        returnValue: _i7.Future<_i4.ForgotPasswordResponseModel>.value(
            _FakeForgotPasswordResponseModel_2(
          this,
          Invocation.method(
            #resetPassword,
            [requestModel],
          ),
        )),
      ) as _i7.Future<_i4.ForgotPasswordResponseModel>);

  @override
  _i7.Future<_i5.EditProfileResponseModel> editProfile(
    String? token,
    _i13.EditProfileRequestModel? requestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [
            token,
            requestModel,
          ],
        ),
        returnValue: _i7.Future<_i5.EditProfileResponseModel>.value(
            _FakeEditProfileResponseModel_3(
          this,
          Invocation.method(
            #editProfile,
            [
              token,
              requestModel,
            ],
          ),
        )),
      ) as _i7.Future<_i5.EditProfileResponseModel>);

  @override
  _i7.Future<String?> logout(String? token) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [token],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);
}
