// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/data/repository/meal_repo/meal_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/api/api_result.dart' as _i4;
import 'package:fitness_app/data/data_source/meal_remote_data_source/meal_remote_data_source.dart'
    as _i2;
import 'package:fitness_app/data/models/meal/meal_model.dart' as _i5;
import 'package:fitness_app/data/models/meal/meals_response_model.dart' as _i8;
import 'package:fitness_app/data/models/meal/meals_tabs_response_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MealRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealRemoteDataSource extends _i1.Mock
    implements _i2.MealRemoteDataSource {
  MockMealRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.Meal?>> getMealDetails(String? mealId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealDetails,
          [mealId],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Meal?>>.value(
            _i6.dummyValue<_i4.Result<_i5.Meal?>>(
          this,
          Invocation.method(
            #getMealDetails,
            [mealId],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Meal?>>);

  @override
  _i3.Future<_i4.Result<List<_i7.Categories>>> fetchMealsTabs() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMealsTabs,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i7.Categories>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.Categories>>>(
          this,
          Invocation.method(
            #fetchMealsTabs,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i7.Categories>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.Meals>>> fetchMealsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMealsByCategory,
          [category],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i8.Meals>>>.value(
            _i6.dummyValue<_i4.Result<List<_i8.Meals>>>(
          this,
          Invocation.method(
            #fetchMealsByCategory,
            [category],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i8.Meals>>>);
}
