// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/data/repository/auth_repo/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/api/api_result.dart' as _i4;
import 'package:fitness_app/data/data_source/auth_data_source/auth_remote_data_source.dart'
    as _i2;
import 'package:fitness_app/data/models/edit_profile/edit_profile_request_model.dart'
    as _i11;
import 'package:fitness_app/data/models/forgot_password/request/forgot_password_request_model.dart'
    as _i8;
import 'package:fitness_app/data/models/forgot_password/request/reset_password_request_model.dart'
    as _i10;
import 'package:fitness_app/data/models/forgot_password/request/verify_code_request_model.dart'
    as _i9;
import 'package:fitness_app/data/models/login/request/login_request_model.dart'
    as _i7;
import 'package:fitness_app/data/models/sign_up/request/sign_up_request_body.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i2.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<String?>> signUp(
          _i5.SignupRequestBody? signupRequestBody) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [signupRequestBody],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #signUp,
            [signupRequestBody],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<String?>> login(
          _i7.LoginRequestModel? loginRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequestModel],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #login,
            [loginRequestModel],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<String?>> forgotPassword(
          _i8.ForgotPasswordRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [requestModel],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #forgotPassword,
            [requestModel],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<String?>> verifyResetCode(
          _i9.VerifyCodeRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [requestModel],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [requestModel],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<String?>> resetPassword(
          _i10.ResetPasswordRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [requestModel],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #resetPassword,
            [requestModel],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<String?>> editProfile(
          _i11.EditProfileRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [requestModel],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #editProfile,
            [requestModel],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<String?>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);
}
