// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/data/repository/home_repo/home_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/api/api_result.dart' as _i4;
import 'package:fitness_app/data/data_source/home_data_source/home_remote_data_source.dart'
    as _i2;
import 'package:fitness_app/data/models/exercise/difficulty_level_model.dart'
    as _i9;
import 'package:fitness_app/data/models/exercise/exercise_by_muscle_and_level_model.dart'
    as _i10;
import 'package:fitness_app/data/models/exercise/exercise_model.dart' as _i5;
import 'package:fitness_app/data/models/home/random_muscle/muscle_model.dart'
    as _i7;
import 'package:fitness_app/data/models/level/level_model.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i2.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.ExerciseModel?>>> getExercise() =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercise,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.ExerciseModel?>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.ExerciseModel?>>>(
          this,
          Invocation.method(
            #getExercise,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.ExerciseModel?>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.MuscleModel?>>> getRandomMuscle() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomMuscle,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i7.MuscleModel?>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.MuscleModel?>>>(
          this,
          Invocation.method(
            #getRandomMuscle,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i7.MuscleModel?>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.MuscleModel?>>> getMuscleGroupById(
          String? muscleGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMuscleGroupById,
          [muscleGroupId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i7.MuscleModel?>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.MuscleModel?>>>(
          this,
          Invocation.method(
            #getMuscleGroupById,
            [muscleGroupId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i7.MuscleModel?>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.LevelModel?>>> getAllLevels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLevels,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i8.LevelModel?>>>.value(
            _i6.dummyValue<_i4.Result<List<_i8.LevelModel?>>>(
          this,
          Invocation.method(
            #getAllLevels,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i8.LevelModel?>>>);

  @override
  _i3.Future<_i4.Result<List<_i9.DifficultyLevelModel?>>> getLevelsByMuscleId(
          String? primeMoverMuscleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLevelsByMuscleId,
          [primeMoverMuscleId],
        ),
        returnValue:
            _i3.Future<_i4.Result<List<_i9.DifficultyLevelModel?>>>.value(
                _i6.dummyValue<_i4.Result<List<_i9.DifficultyLevelModel?>>>(
          this,
          Invocation.method(
            #getLevelsByMuscleId,
            [primeMoverMuscleId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i9.DifficultyLevelModel?>>>);

  @override
  _i3.Future<_i4.Result<List<_i10.ExerciseByMuscleAndLevelModel>>>
      getExerciseByMuscleAndLevel(
    String? primeMoverMuscleId,
    String? difficultyLevelId,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getExerciseByMuscleAndLevel,
              [
                primeMoverMuscleId,
                difficultyLevelId,
              ],
            ),
            returnValue: _i3.Future<
                    _i4.Result<List<_i10.ExerciseByMuscleAndLevelModel>>>.value(
                _i6.dummyValue<
                    _i4.Result<List<_i10.ExerciseByMuscleAndLevelModel>>>(
              this,
              Invocation.method(
                #getExerciseByMuscleAndLevel,
                [
                  primeMoverMuscleId,
                  difficultyLevelId,
                ],
              ),
            )),
          ) as _i3
              .Future<_i4.Result<List<_i10.ExerciseByMuscleAndLevelModel>>>);
}
